### ISSUE TITLE
issues with Arduino communication in 2.8

### ISSUE THREAD

**Issue by LaurenzMuessig** [bonsai-rx/bonsai#1514]
Hi,

First of all thank you guys for putting together such an amazing tool for running experiments. I have been using it for years and it has been incredibly helpful.

I have a very simple workflow. Just keydown-string-SerialWriteLine plus a CreateSerialPort. On my Arduino I have a simple routine that just checks whether what's supposed to have been sent by SerialWriteLine has been received and then sets a pin to HIGH. It works fine on a machine running Bonsai 2.6.2 but on a different one running 2.8 it crashes  immediately with the following:

Bonsai.WorkflowRuntimeException: The given port name does not start with COM/com or does not resolve to a valid serial port.
Parameter name: portName ---> System.ArgumentException: The given port name does not start with COM/com or does not resolve to a valid serial port.
Parameter name: portName
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at Bonsai.IO.Ports.SerialPortManager.ReserveConnection(String portName, SerialPortConfiguration serialPortConfiguration)
   at Bonsai.IO.Ports.ObservableSerialPort.<>c__DisplayClass2_0`1.<WriteLine>b__0()
   at System.Reactive.Linq.ObservableImpl.Using`2._.Run()
   --- End of inner exception stack trace ---

Also I cannot use SerialWrite instead of SerialWriteLine as the workflow complains:
Bonsai.WorkflowBuildException: No method overload found for the given arguments. ---> System.InvalidOperationException: No method overload found for the given arguments.
   at Bonsai.Expressions.ExpressionBuilder.BuildCall(Expression instance, IEnumerable`1 methods, Expression[] arguments)
   at Bonsai.Expressions.InspectBuilder.Build(IEnumerable`1 arguments)
   at Bonsai.Expressions.ExpressionBuilderGraphExtensions.Build(ExpressionBuilderGraph source, IBuildContext buildContext)
   --- End of inner exception stack trace ---
   at Bonsai.Expressions.ExpressionBuilderGraphExtensions.Build(ExpressionBuilderGraph source, IBuildContext buildContext)
   at Bonsai.Expressions.ExpressionBuilderGraphExtensions.BuildNested(ExpressionBuilderGraph source, IEnumerable`1 arguments, IBuildContext buildContext)
   at Bonsai.Expressions.ExpressionBuilderGraphExtensions.Build(ExpressionBuilderGraph source, ExpressionBuilder buildTarget, IEnumerable`1 buildArguments)
   at Bonsai.Expressions.ExpressionBuilderGraphExtensions.BuildObservable(ExpressionBuilderGraph source)
   at Bonsai.Editor.EditorForm.<StartWorkflow>b__131_0()
   at System.Reactive.Linq.ObservableImpl.Using`2._.Run()

Any help with what I am doing wrong is greatly appreciated.

Cheers

Laurenz

**Comment by glopesdev** [comment]
@LaurenzMuessig can you share a simple workflow that reproduces the problem? We did revamp a bit the way the Arduino module works for 2.8 to allow it to run on Linux so there might be issues.

**Comment by LaurenzMuessig** [comment]
Hi @glopesdev,
Thanks for your quick response. The issue fixed itself after rebooting the computer. Not sure what happened but it's now working. I have a different issue now, but I'll open a new issue for that. Cheers

**Comment by ytjiang-98** [comment]
Hi! I have met the same problem with you. When I tried to connect with arduino mega COM , the bonsai always reported " The given port name does not start with COM/com or does not resolve to a valid serial port.". And I have tried update the bonsai to the latest version 2.90, and restart my computer for several times ,it still doesn't work. Could you tell me what else can I do, or if you met the same problem again.

**Comment by banchan86** [comment]
> Hi! I have met the same problem with you. When I tried to connect with arduino mega COM , the bonsai always reported " The given port name does not start with COM/com or does not resolve to a valid serial port.". And I have tried update the bonsai to the latest version 2.90, and restart my computer for several times ,it still doesn't work. Could you tell me what else can I do, or if you met the same problem again.

hi @ytjiang-98 can you provide more details:
- Have you installed [firmata](https://bonsai-rx.org/docs/tutorials/acquisition.html#arduino-acquisition) on the board?
- Which version of the arduino mega are you using?
- Just to confirm, you are trying this on Windows, right?
